/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oodj_assignment;

import java.net.URL;
import oodj_assignment.Enums.Status;

import java.util.Date;
import java.util.Calendar;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
/**
 *
 * @author wsc2010
 */
public class CreateOrder extends javax.swing.JDialog {

    /**
     * Creates new form CreateOrder
     */
    Customer cust = null;
    
    Order ord = new Order();
    
    public CreateOrder(java.awt.Frame parent, boolean modal, Customer currUser) {
        super(parent, modal);
        initComponents();
        
        this.cust = currUser;
        
        Calendar date = Calendar.getInstance();
        
        ord.setOrderDateTime(date.getTime());
        
        date.add(Calendar.DAY_OF_MONTH, 1);
        Date tmr = date.getTime();
        
        cldPickupDate.setMaxDayCharacters(1);
        cldPickupDate.setMinSelectableDate(tmr);
        cldPickupDate.setDate(tmr);
        
        // Set icon jframe icon
        URL iconURL = getClass().getResource("/img/main_icon.jpg");
        ImageIcon icon = new ImageIcon(iconURL);
        setIconImage(icon.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDimensions = new javax.swing.JLabel();
        lblWeight = new javax.swing.JLabel();
        btnCreate = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        txtLength = new javax.swing.JTextField();
        txtWidth = new javax.swing.JTextField();
        txtHeight = new javax.swing.JTextField();
        lblLength = new javax.swing.JLabel();
        lblWidth = new javax.swing.JLabel();
        lblHeight = new javax.swing.JLabel();
        txtWeight = new javax.swing.JTextField();
        lblSenderAddress = new javax.swing.JLabel();
        lblRecipientAddress = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtSenderAddress = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtRecipientAddress = new javax.swing.JTextArea();
        lblRecipientName = new javax.swing.JLabel();
        txtRecipientName = new javax.swing.JTextField();
        lblSenderName = new javax.swing.JLabel();
        txtSenderName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        lblPrice = new javax.swing.JLabel();
        lblSenderName1 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        cldPickupDate = new com.toedter.calendar.JCalendar();
        btnSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblDimensions.setText("Dimensions (cm) :");

        lblWeight.setText("Weight (kg) :");

        btnCreate.setText("Create and Pay");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        txtLength.setText("2");
        txtLength.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLengthKeyTyped(evt);
            }
        });

        txtWidth.setText("3");
        txtWidth.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtWidthKeyTyped(evt);
            }
        });

        txtHeight.setText("4");
        txtHeight.setToolTipText("");
        txtHeight.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtHeightKeyTyped(evt);
            }
        });

        lblLength.setText("L :");

        lblWidth.setText("W :");

        lblHeight.setText("H :");

        txtWeight.setText("1");
        txtWeight.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtWeightKeyTyped(evt);
            }
        });

        lblSenderAddress.setText("Sender Address :");

        lblRecipientAddress.setText("Recipient Address :");

        txtSenderAddress.setColumns(20);
        txtSenderAddress.setLineWrap(true);
        txtSenderAddress.setRows(5);
        txtSenderAddress.setText("CustomerAddress");
        txtSenderAddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSenderAddressKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(txtSenderAddress);

        txtRecipientAddress.setColumns(20);
        txtRecipientAddress.setLineWrap(true);
        txtRecipientAddress.setRows(5);
        txtRecipientAddress.setText("asfd");
        txtRecipientAddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRecipientAddressKeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(txtRecipientAddress);

        lblRecipientName.setText("Recipient Name :");

        txtRecipientName.setText("asdf");
        txtRecipientName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRecipientNameKeyTyped(evt);
            }
        });

        lblSenderName.setText("Sender Name :");

        txtSenderName.setText("CustomerName");
        txtSenderName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSenderNameKeyTyped(evt);
            }
        });

        jLabel1.setText("Pickup Date :");

        txtPrice.setText("2.50");
        txtPrice.setEnabled(false);

        lblPrice.setText("Price (RM) :");

        lblSenderName1.setText("Your Email :");

        txtEmail.setText("Email");
        txtEmail.setEnabled(false);

        cldPickupDate.setTodayButtonText("Tomorrow");
        cldPickupDate.setWeekOfYearVisible(false);

        btnSave.setText("Save For Later");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblSenderName)
                                .addGap(10, 10, 10)
                                .addComponent(txtSenderName, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblRecipientName)
                                    .addComponent(lblSenderAddress)
                                    .addComponent(lblRecipientAddress))
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane1)
                                    .addComponent(jScrollPane2)
                                    .addComponent(txtRecipientName, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblSenderName1)
                                .addGap(10, 10, 10)
                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cldPickupDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblDimensions)
                            .addComponent(lblWeight)
                            .addComponent(lblPrice))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblLength)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtLength, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(lblWidth)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtWidth, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblHeight)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtHeight, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCreate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)))
                .addGap(48, 48, 48))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSenderName1)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSenderName)
                    .addComponent(txtSenderName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSenderAddress)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblRecipientName)
                            .addComponent(txtRecipientName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRecipientAddress)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cldPickupDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDimensions)
                            .addComponent(txtLength, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtWidth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLength)
                            .addComponent(lblWidth)
                            .addComponent(lblHeight))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblWeight)
                            .addComponent(txtWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPrice)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCreate)
                        .addGap(9, 9, 9)
                        .addComponent(btnSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancel)))
                .addGap(55, 55, 55))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        if (GlobalMethods.isEmpty(txtSenderName.getText()) ||
                GlobalMethods.isEmpty(txtSenderAddress.getText()) ||
                GlobalMethods.isEmpty(txtRecipientName.getText()) ||
                GlobalMethods.isZero(txtLength.getText()) ||
                GlobalMethods.isZero(txtWidth.getText()) ||
                GlobalMethods.isZero(txtHeight.getText()) ||
                GlobalMethods.isZero(txtWeight.getText())) {
            if (GlobalMethods.isEmpty(txtSenderName.getText()) ||
                GlobalMethods.isEmpty(txtSenderAddress.getText()) ||
                GlobalMethods.isEmpty(txtRecipientName.getText())) {
                JOptionPane.showMessageDialog(null, "There Are Empty Fields", "Unable to Create", JOptionPane.ERROR_MESSAGE);
            }
            else {
                JOptionPane.showMessageDialog(null, "There Are Zero Values", "Unable to Create", JOptionPane.ERROR_MESSAGE);
            }
        }
        else {
            updatePrice();
        
            int reply = JOptionPane.showConfirmDialog(null, "Confirm Order?", "Confirm Order", JOptionPane.YES_NO_OPTION);
            if (reply == JOptionPane.YES_OPTION) {
                ord.setCustomer(cust.getEmail());
                ord.setPrice(Double.parseDouble(txtPrice.getText()));
                ord.setSenderName(txtSenderName.getText());
                ord.setSenderAddress(txtSenderAddress.getText());
                ord.setRecipientName(txtRecipientName.getText());
                ord.setRecipientAddress(txtRecipientAddress.getText());
                Dimension dim = new Dimension(Double.parseDouble(txtLength.getText()), Double.parseDouble(txtWidth.getText()), Double.parseDouble(txtHeight.getText()));
                ord.setDimensions(dim);
                ord.setWeight(Double.parseDouble(txtWeight.getText()));
                ord.setPickupDate(cldPickupDate.getDate());
                ord.setStatus(Status.AWAITING_CONFIRMATION);
                
                ord.create();
            
                JOptionPane.showMessageDialog(null, "Order Succesfully Created", "Order Created", JOptionPane.INFORMATION_MESSAGE);
            }
        }
        
        
    }//GEN-LAST:event_btnCreateActionPerformed

    private void txtLengthKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLengthKeyTyped
        // TODO add your handling code here:
        GlobalMethods.numericOnlyText(txtLength, evt);
        updatePrice();
    }//GEN-LAST:event_txtLengthKeyTyped

    private void txtWidthKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtWidthKeyTyped
        // TODO add your handling code here:
        GlobalMethods.numericOnlyText(txtWidth, evt);
        updatePrice();
    }//GEN-LAST:event_txtWidthKeyTyped

    private void txtHeightKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHeightKeyTyped
        // TODO add your handling code here:
        GlobalMethods.numericOnlyText(txtHeight, evt);
        updatePrice();
    }//GEN-LAST:event_txtHeightKeyTyped

    private void txtWeightKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtWeightKeyTyped
        // TODO add your handling code here:
        GlobalMethods.numericOnlyText(txtWeight, evt);
        updatePrice();
    }//GEN-LAST:event_txtWeightKeyTyped

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        updatePrice();
        
        int reply = JOptionPane.showConfirmDialog(null, "Save For Later?", "Save", JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {
            ord.setCustomer(cust.getEmail());
            ord.setPrice(Double.parseDouble(txtPrice.getText()));
            ord.setSenderName(txtSenderName.getText());
            ord.setSenderAddress(txtSenderAddress.getText());
            ord.setRecipientName(txtRecipientName.getText());
            ord.setRecipientAddress(txtRecipientAddress.getText());
            Dimension dim = new Dimension(Double.parseDouble(txtLength.getText()), Double.parseDouble(txtWidth.getText()), Double.parseDouble(txtHeight.getText()));
            ord.setDimensions(dim);
            ord.setWeight(Double.parseDouble(txtWeight.getText()));
            ord.setPickupDate(cldPickupDate.getDate());
            ord.setStatus(Status.UNPAID);
            
            ord.create();
            
            JOptionPane.showMessageDialog(null, "Order Saved", "Save Order", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
        }
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void txtSenderNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSenderNameKeyTyped
        // TODO add your handling code here:
        GlobalMethods.noPipeText(txtSenderName, evt);
    }//GEN-LAST:event_txtSenderNameKeyTyped

    private void txtSenderAddressKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSenderAddressKeyTyped
        // TODO add your handling code here:
        GlobalMethods.noPipeText(txtSenderAddress, evt);
    }//GEN-LAST:event_txtSenderAddressKeyTyped

    private void txtRecipientNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRecipientNameKeyTyped
        // TODO add your handling code here:
        GlobalMethods.noPipeText(txtRecipientName, evt);
    }//GEN-LAST:event_txtRecipientNameKeyTyped

    private void txtRecipientAddressKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRecipientAddressKeyTyped
        // TODO add your handling code here:
        GlobalMethods.noPipeText(txtRecipientAddress, evt);
    }//GEN-LAST:event_txtRecipientAddressKeyTyped

    
    private void updatePrice() {
        double l = Double.parseDouble(txtLength.getText());
        double w = Double.parseDouble(txtWidth.getText());
        double h = Double.parseDouble(txtHeight.getText());
        Dimension dim = new Dimension(l, w, h);
        double weight = Double.parseDouble(txtWeight.getText());
        
        txtPrice.setText(String.format("%.2f", ord.calcPrice(dim, weight)));
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnSave;
    private com.toedter.calendar.JCalendar cldPickupDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblDimensions;
    private javax.swing.JLabel lblHeight;
    private javax.swing.JLabel lblLength;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblRecipientAddress;
    private javax.swing.JLabel lblRecipientName;
    private javax.swing.JLabel lblSenderAddress;
    private javax.swing.JLabel lblSenderName;
    private javax.swing.JLabel lblSenderName1;
    private javax.swing.JLabel lblWeight;
    private javax.swing.JLabel lblWidth;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtHeight;
    private javax.swing.JTextField txtLength;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextArea txtRecipientAddress;
    private javax.swing.JTextField txtRecipientName;
    private javax.swing.JTextArea txtSenderAddress;
    private javax.swing.JTextField txtSenderName;
    private javax.swing.JTextField txtWeight;
    private javax.swing.JTextField txtWidth;
    // End of variables declaration//GEN-END:variables
}
