/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oodj_assignment;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Toolkit;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class ManageReportForm extends javax.swing.JFrame {
    DefaultTableModel mymodel;
    DefaultTableModel mymodel1;
    Report report;
    
    /**
     * Creates new form ManageReportForm
     */
    public ManageReportForm() {
        report = new Report();
        initComponents();
        setVisible(true);
        fillOrderTable();
        fillDeliveryStaffTable();
        styleTable();
        lblDateTime.setText(report.reportDate);
        lblDateTime1.setText(report.reportDate);
        setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
        setResizable(false);
        setTitle("Report");
        // Set icon jframe icon
        URL iconURL = getClass().getResource("/img/main_icon.jpg");
        ImageIcon icon = new ImageIcon(iconURL);
        setIconImage(icon.getImage());
        
        /* center the jframe form */
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOrder = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblTotalSales = new javax.swing.JLabel();
        lblDateTime = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDeliveryStaff = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblDateTime1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jdcEndDate = new datechooser.beans.DateChooserCombo();
        jLabel5 = new javax.swing.JLabel();
        btnPrint = new javax.swing.JButton();
        jdcStartDate = new datechooser.beans.DateChooserCombo();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(815, 770));
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tblOrder.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        tblOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }

        )
        {public boolean isCellEditable(int row, int column){return false;}}
    );
    tblOrder.setIntercellSpacing(new java.awt.Dimension(0, 0));
    tblOrder.setRowHeight(30);
    tblOrder.setShowVerticalLines(false);
    jScrollPane1.setViewportView(tblOrder);

    jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
    jLabel1.setText("Courier Service Report");

    jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
    jLabel2.setText("Total Sales :");

    lblTotalSales.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

    lblDateTime.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
    lblDateTime.setToolTipText("");

    jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
    jLabel3.setText("Date Time:");

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(jScrollPane1)
                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                    .addComponent(jLabel1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 327, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(lblDateTime, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                    .addComponent(jLabel2)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(lblTotalSales, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addContainerGap())
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
            .addGap(12, 12, 12)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1)
                .addComponent(jLabel3)
                .addComponent(lblDateTime, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel2)
                .addComponent(lblTotalSales, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    jTabbedPane1.addTab("Sales Report", jPanel1);

    tblDeliveryStaff.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
    tblDeliveryStaff.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null}
        },
        new String [] {
            "Title 1", "Title 2", "Title 3", "Title 4"
        }

    )
    {public boolean isCellEditable(int row, int column){return false;}}
    );
    tblDeliveryStaff.setIntercellSpacing(new java.awt.Dimension(0, 0));
    tblDeliveryStaff.setRowHeight(30);
    tblDeliveryStaff.setShowVerticalLines(false);
    jScrollPane2.setViewportView(tblDeliveryStaff);

    jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
    jLabel6.setText("Delivery Staff Report");

    jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
    jLabel7.setText("Date Time:");

    lblDateTime1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
    lblDateTime1.setToolTipText("");

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel2Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel6)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 344, Short.MAX_VALUE)
            .addComponent(jLabel7)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(lblDateTime1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap())
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 742, Short.MAX_VALUE)
                .addGap(12, 12, 12)))
    );
    jPanel2Layout.setVerticalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel2Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lblDateTime1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(575, Short.MAX_VALUE))
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE)))
    );

    jTabbedPane1.addTab("Delivery Staff Report", jPanel2);

    jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
    jLabel4.setText("Start Date");

    try {
        jdcEndDate.setDefaultPeriods(new datechooser.model.multiple.PeriodSet());
    } catch (datechooser.model.exeptions.IncompatibleDataExeption e1) {
        e1.printStackTrace();
    }
    jdcEndDate.setFieldFont(new java.awt.Font("Times New Roman", java.awt.Font.PLAIN, 18));
    jdcEndDate.addCommitListener(new datechooser.events.CommitListener() {
        public void onCommit(datechooser.events.CommitEvent evt) {
            jdcEndDateOnCommit(evt);
        }
    });

    jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
    jLabel5.setText("End Date");

    btnPrint.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
    btnPrint.setText("Print");
    btnPrint.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnPrintActionPerformed(evt);
        }
    });

    try {
        jdcStartDate.setDefaultPeriods(new datechooser.model.multiple.PeriodSet());
    } catch (datechooser.model.exeptions.IncompatibleDataExeption e1) {
        e1.printStackTrace();
    }
    jdcStartDate.setFieldFont(new java.awt.Font("Times New Roman", java.awt.Font.PLAIN, 18));
    jdcStartDate.addCommitListener(new datechooser.events.CommitListener() {
        public void onCommit(datechooser.events.CommitEvent evt) {
            jdcStartDateOnCommit(evt);
        }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jdcStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jdcEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 771, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createSequentialGroup()
                    .addGap(334, 334, 334)
                    .addComponent(btnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap(42, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jdcStartDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jdcEndDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
            .addComponent(btnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 647, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(110, 110, 110))
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        // TODO add your handling code here:
        printToPdf();
    }//GEN-LAST:event_btnPrintActionPerformed

    private void jdcStartDateOnCommit(datechooser.events.CommitEvent evt) {//GEN-FIRST:event_jdcStartDateOnCommit
        // TODO add your handling code here:
        if (jdcStartDate.getText().equals("")){
            report.setStartDate(null);
        }else {
            report.setStartDate(jdcStartDate.getText());
        }
        fillOrderTable();
        fillDeliveryStaffTable();
    }//GEN-LAST:event_jdcStartDateOnCommit

    private void jdcEndDateOnCommit(datechooser.events.CommitEvent evt) {//GEN-FIRST:event_jdcEndDateOnCommit
        // TODO add your handling code here:
        if (jdcEndDate.getText().equals("")){
            report.setEndDate(null);
        }else {
            report.setEndDate(jdcEndDate.getText());
        }
        fillOrderTable();
        fillDeliveryStaffTable();
    }//GEN-LAST:event_jdcEndDateOnCommit

    private void styleTable(){
        tblOrder.getTableHeader().setFont(new Font("Cambria", Font.BOLD, 16));
        tblOrder.getTableHeader().setOpaque(false);
        tblOrder.getTableHeader().setBackground(new Color(32, 136, 203));
        tblOrder.getTableHeader().setForeground(Color.white);
        tblOrder.getTableHeader().setPreferredSize(new Dimension(0,40));
        tblOrder.getColumnModel().getColumn(0).setPreferredWidth(30);
        tblOrder.getColumnModel().getColumn(1).setPreferredWidth(50);
        tblOrder.getColumnModel().getColumn(2).setPreferredWidth(10);
        tblOrder.getColumnModel().getColumn(3).setPreferredWidth(20);
        tblOrder.getColumnModel().getColumn(4).setPreferredWidth(50);
        tblOrder.getColumnModel().getColumn(5).setPreferredWidth(8);
        
        tblDeliveryStaff.getTableHeader().setFont(new Font("Cambria", Font.BOLD, 16));
        tblDeliveryStaff.getTableHeader().setOpaque(false);
        tblDeliveryStaff.getTableHeader().setBackground(new Color(32, 136, 203));
        tblDeliveryStaff.getTableHeader().setForeground(Color.white);
        tblDeliveryStaff.getTableHeader().setPreferredSize(new Dimension(0,40));

    }
    
    private void fillDeliveryStaffTable() {
        String []columnNames = {"Staff Email","Total Package Picked up","Total Package Delivered"};
        mymodel1 = (DefaultTableModel) tblDeliveryStaff.getModel();
        mymodel1.setColumnIdentifiers(columnNames); 
        //display columnnames on jtable
        mymodel1.setRowCount(0);            
        tblDeliveryStaff.revalidate();

        Object records[] = report.generateDeliveryStaffReport();

        for(int index=0;index<records.length;index++){
            String eachline = records[index].toString();
            String []row = eachline.split(",");
            String datarow[] = {row[0],row[1],row[2]};
            mymodel1.addRow(datarow);

        }

    }
    
    private void fillOrderTable() {
        //fill table with column name
            String []columnNames = {"Oder ID","Order DateTime","Price (RM)","Sender Name","Dimensions (CM)","Weight"};
            mymodel = (DefaultTableModel) tblOrder.getModel();
            mymodel.setColumnIdentifiers(columnNames); 
            //display columnnames on jtable
            mymodel.setRowCount(0);            
            tblOrder.revalidate();
            
            Object records[] = report.generateSalesReport();
            double sum = 0;
            for(int index=0;index<records.length;index++){
                String eachline = records[index].toString();
                String []row = eachline.split("\\|");
                String datarow[] = {row[0],row[1],row[2],row[3],row[4],row[5]};
                mymodel.addRow(datarow);

                sum += Double.parseDouble(row[2]);
            }
            lblTotalSales.setText("RM " + sum);
                
    }

    private void printToPdf() {
        
        PrinterJob job = PrinterJob.getPrinterJob();
        job.setJobName("Print Data");
        
        job.setPrintable(new Printable(){
            public int print(Graphics pg,PageFormat pf, int pageNum){
                pf.setOrientation(PageFormat.LANDSCAPE);

                if(pageNum>0){
                    return Printable.NO_SUCH_PAGE;
                }

                Graphics2D g2 = (Graphics2D)pg;
                g2.translate(pf.getImageableX(), pf.getImageableY());
                g2.scale(0.77,0.77);

                if (jTabbedPane1.getSelectedIndex() == 0){
                    jPanel1.paint(g2); 
                }else {
                    jPanel2.paint(g2); 
                }
                       
                return Printable.PAGE_EXISTS;
            }
        });
         
        boolean ok = job.printDialog();
        if(ok){
            try{
                job.print();
            }
            catch (PrinterException ex){
                System.out.println(ex);
            }
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPrint;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private datechooser.beans.DateChooserCombo jdcEndDate;
    private datechooser.beans.DateChooserCombo jdcStartDate;
    private javax.swing.JLabel lblDateTime;
    private javax.swing.JLabel lblDateTime1;
    private javax.swing.JLabel lblTotalSales;
    private javax.swing.JTable tblDeliveryStaff;
    private javax.swing.JTable tblOrder;
    // End of variables declaration//GEN-END:variables
}
